project_id = "prfmejalekmbzaorrtmu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.batch-call]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324