// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prfmejalekmbzaorrtmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZm1lamFsZWttYnphb3JydG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjY0ODEsImV4cCI6MjA3NDAwMjQ4MX0.mD8dE7-hJMpPTdKV9V3YHTzSbo_N-nj0dE6hj0P5-UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});